import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Baleno.module.css'
import Row from 'react-bootstrap/Row';
import Col from 'react-bootstrap/Col';
import Container from 'react-bootstrap/Container';
import 'bootstrap/dist/css/bootstrap.min.css';
import Carousel from 'react-multi-carousel';
import 'react-multi-carousel/lib/styles.css';
import Button from 'react-bootstrap/Button';
import Form from 'react-bootstrap/Form';
import Accordion from 'react-bootstrap/Accordion';
import ReadMoreReact from 'read-more-react';
import React, {useState} from 'react';
import axios from 'axios';
const responsive = {
  superLargeDesktop: {
    // the naming can be any, depends on you.
    breakpoint: { max: 4000, min: 3000 },
    items: 5
  },
  desktop: {
    breakpoint: { max: 3000, min: 1024 },
    items: 3
  },
  tablet: {
    breakpoint: { max: 1024, min: 464 },
    items: 2
  },
  mobile: {
    breakpoint: { max: 464, min: 0 },
    items: 1
  }
};

  

export default function Home() 

{
  {
    const [reply] = useState('');
  
  }
  
     
  const [likes, setLikes] = React.useState(0);
  

  function handleClick() {
    setLikes(likes + 1);
    
  }
  const [likes2, setLikes2] = React.useState(0);
  

  function handleClick2() {
    setLikes2(likes2 + 1);
    
  }
  const [likes3, setLikes3] = React.useState(0);
  

  function handleClick3() {
    setLikes3(likes3 + 1);
    
  }


    const [formValue, setformValue] = React.useState({
      email: '',
      password: ''
    });
  
    const handleSubmit = (event) => {
      //
    }
  const handleChange = (event) => {
    setformValue({
      ...formValue,
      [event.target.name]: event.target.value
    });
  }
  

  return (
    
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.nav}>
          <img src="logo.png"/>
          <diV className={styles.nav2}>

        
          <Form.Control
              type="search"
              placeholder="Search"
              className="me-2"
              aria-label="Search"
              
            />
            <Button variant="outline-success">Search</Button>
            </diV>
    </div>
      <Container>
        <div className={styles.c2}>
         
        <Row>
            <Col md={9} sm={12}>
                <div className={styles.bar}>
                    <div className={styles.bar1}>
                        <p>Baleno 2015-2022</p>
                        <p>Safety</p>
                        <hr></hr>
                    </div>
                </div>
                <hr></hr>
              <h3 className={styles.h3}>Q.How safe Baleno Zeta on Highway ?</h3>

                               <p className={styles.bar2}><svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-bell" viewBox="0 0 16 16">
                                <path d="M8 16a2 2 0 0 0 2-2H6a2 2 0 0 0 2 2zM8 1.918l-.797.161A4.002 4.002 0 0 0 4 6c0 .628-.134 2.197-.459 3.742-.16.767-.376 1.566-.663 2.258h10.244c-.287-.692-.502-1.49-.663-2.258C12.134 8.197 12 6.628 12 6a4.002 4.002 0 0 0-3.203-3.92L8 1.917zM14.22 12c.223.447.481.801.78 1H1c.299-.199.557-.553.78-1C2.68 10.2 3 6.88 3 6c0-2.42 1.72-4.44 4.005-4.901a1 1 0 1 1 1.99 0A5.002 5.002 0 0 1 13 6c0 .88.32 4.2 1.22 6z"/>
                                 </svg>2.1k Views | <span><svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-chat-left-text-fill" viewBox="0 0 16 16">
                                    <path d="M0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H4.414a1 1 0 0 0-.707.293L.854 15.146A.5.5 0 0 1 0 14.793V2zm3.5 1a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 2.5a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-5z"/>
                                    </svg>Add Answer</span></p>
                                    <hr></hr>
                                    <p className={styles.bar2}>7 Answer</p> 
                                    <Row>
                                <Col md={1} sm={1} xs={1}>
                                <div className={styles.box1}>
                                    <span>
                                    <h1 className={styles.h21}>R</h1>
                                    </span>
                                    </div>
                                    
                                </Col>
                                <Col md={11} sm={11} xs={11}>
                                    <div className={styles.box2}>
                                        <div className={styles.edit23}>
                                    <p className={styles.h31}>Rishabh Rai</p><p>| 1 month ago</p>
                                    </div>
                                    
                                      <div className={styles.ans}>
                                           <p>All varients of baleno comes with standard safety equipment like front dual airbags ebd abs etc..., if you search on internet there are some videos showing alott off damage on baleno in minor accident, this is because every manufacturer have different approch to provide safety, in maruti case they gave alot of crumple Zone to absorb any hits. If you open hood and see engine bay there is alot of space between radiator and enginr, in petrol its huge. This crumple Zone gets damaged in small accidents also but cost of repair is not high. My bumper got hit once(preety bad).Cost to replace it is 8k for entire piece. Compara<span>...Read more</span></p>
                                                            
                                           </div>
                                           <div className={styles.ans3}>
                                    <div>
                                      <Button className={styles.likebtn23} onClick={handleClick} ><svg className={styles.ans412} xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
                                    <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                                    </svg> </Button> {likes} | <div> 
                                       </div>
                                                    <Accordion defaultActiveKey="0">
                                                <Accordion.Item eventKey="0">
                                                <Accordion.Header className={styles.ans5} onChange={(e)=>{setReply(e.target.value)}}>Reply</Accordion.Header>
                                                    <svg className={styles.ans6}  xmlns="http://www.w3.org/2000/svg" width="10" height="16" fill="currentColor" class="bi bi-flag-fill" viewBox="0 0 16 16">
                                                    <path d="M14.778.085A.5.5 0 0 1 15 .5V8a.5.5 0 0 1-.314.464L14.5 8l.186.464-.003.001-.006.003-.023.009a12.435 12.435 0 0 1-.397.15c-.264.095-.631.223-1.047.35-.816.252-1.879.523-2.71.523-.847 0-1.548-.28-2.158-.525l-.028-.01C7.68 8.71 7.14 8.5 6.5 8.5c-.7 0-1.638.23-2.437.477A19.626 19.626 0 0 0 3 9.342V15.5a.5.5 0 0 1-1 0V.5a.5.5 0 0 1 1 0v.282c.226-.079.496-.17.79-.26C4.606.272 5.67 0 6.5 0c.84 0 1.524.277 2.121.519l.043.018C9.286.788 9.828 1 10.5 1c.7 0 1.638-.23 2.437-.477a19.587 19.587 0 0 0 1.349-.476l.019-.007.004-.002h.001"/>
                                                    </svg>
                                                  <Accordion.Body>
                                                              <div className={styles.mb-3}>
                                                                <Form>
                                                            <Form.Group className="mb-3" controlId="formBasicEmail" >
                                                              <Form.Label>Add your Answer</Form.Label>
                                                              <Form.Control  onChange={handleChange} type="text" as="textarea" rows={3} placeholder="Have some thing to say..." />
                                                          </Form.Group>
                                                        </Form>
                                                        <div className={styles.btn}>
                                                            <Button variant="primary" type="cancle">
                                                                  Cancle
                                                            </Button>
                                                             
                                                            <Button variant="primary" type="submit" href='http://localhost:3000/mygarage' >
                                                                  Submit 
                                                            </Button>
                                                        </div>
                                                                </div>
                                                  </Accordion.Body>
                                                </Accordion.Item>
                                                </Accordion>
                                    </div>
                                    </div>
                                    
                                 </div>
                               
                                </Col>
                                </Row>   
                                <Row>
                                <Col md={1} sm={1} xs={1}>
                                <div className={styles.box12}>
                                    <span>
                                    <h1 className={styles.h21}>R</h1>
                                    </span>
                                    </div>
                                    
                                </Col>
                                <Col md={11} sm={11} xs={11}>
                                    <div className={styles.box2}>
                                        <div className={styles.edit23}>
                                    <p className={styles.h31}>Rishu</p><p>| 1 month ago</p>
                                    </div>
                                    
                                      <div className={styles.ans}>
                                           <p>All varients of baleno comes with standard safety equipment like front dual airbags ebd abs etc..., if you search on internet ashchds fyusbgsdb huddsiubg  </p>
                                          
                                           </div>
                                      
                                           <div className={styles.ans3}>
                                    <div>
                                      <Button className={styles.likebtn23} onClick={handleClick2} ><svg className={styles.ans41} xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
                                    <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                                    </svg> </Button> {likes2} |
                                                    <Accordion defaultActiveKey="0">
                                                <Accordion.Item eventKey="0">
                                                <Accordion.Header className={styles.ans5} >Reply</Accordion.Header>
                                                    <svg className={styles.ans61}  xmlns="http://www.w3.org/2000/svg" width="10" height="16" fill="currentColor" class="bi bi-flag-fill" viewBox="0 0 16 16">
                                                    <path d="M14.778.085A.5.5 0 0 1 15 .5V8a.5.5 0 0 1-.314.464L14.5 8l.186.464-.003.001-.006.003-.023.009a12.435 12.435 0 0 1-.397.15c-.264.095-.631.223-1.047.35-.816.252-1.879.523-2.71.523-.847 0-1.548-.28-2.158-.525l-.028-.01C7.68 8.71 7.14 8.5 6.5 8.5c-.7 0-1.638.23-2.437.477A19.626 19.626 0 0 0 3 9.342V15.5a.5.5 0 0 1-1 0V.5a.5.5 0 0 1 1 0v.282c.226-.079.496-.17.79-.26C4.606.272 5.67 0 6.5 0c.84 0 1.524.277 2.121.519l.043.018C9.286.788 9.828 1 10.5 1c.7 0 1.638-.23 2.437-.477a19.587 19.587 0 0 0 1.349-.476l.019-.007.004-.002h.001"/>
                                                    </svg>
                                                  <Accordion.Body>
                                                    <div className={styles.mb-3}>
                                                    <Form>
                                                <Form.Group className="mb-3" controlId="formBasicEmail">
                                                  <Form.Label>Add your Answer</Form.Label>
                                                  <Form.Control type="text" as="textarea" rows={3} placeholder="Have some thing to say..." />
                                               </Form.Group>
                                            </Form>
                                            <div className={styles.btn}>
                                                <Button variant="primary" type="cancle">
                                                      Cancle
                                                </Button>

                                                <Button variant="primary" type="submit">
                                                      Submit 
                                                </Button>
                                            </div>
                                                    </div>
                                                     </Accordion.Body>
                                                </Accordion.Item>
                                                </Accordion>
                                    </div>
                                    </div>
                                    
                                 </div>
                               
                                         
                                </Col>
                                </Row>  
                                <Row>
                                <Col md={1} sm={1} xs={1}>
                                <div className={styles.box1}>
                                    <span>
                                    <h1 className={styles.h21}>R</h1>
                                    </span>
                                    </div>
                                    
                                </Col>
                                <Col md={11} sm={11} xs={11}>
                                    <div className={styles.box2}>
                                        <div className={styles.edit23}>
                                    <p className={styles.h31}>Rishu</p><p>| 1 month ago</p>
                                    </div>
                                    
                                      <div className={styles.ans}>
                                           <p>Very safe, even at highspeed car maintain  ist stability ABS works well.. </p>
                                         
                                           </div>
                                      
                                           <div className={styles.ans3}>
                                    <div>
                                      <Button className={styles.likebtn2} onClick={handleClick3} ><svg className={styles.ans4} xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
                                    <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                                    </svg> </Button> {likes3} | 
                                                    <Accordion defaultActiveKey="0">
                                                <Accordion.Item eventKey="0">
                                                <Accordion.Header className={styles.ans5} >Reply</Accordion.Header>
                                                    <svg className={styles.ans612}  xmlns="http://www.w3.org/2000/svg" width="10" height="16" fill="currentColor" class="bi bi-flag-fill" viewBox="0 0 16 16">
                                                    <path d="M14.778.085A.5.5 0 0 1 15 .5V8a.5.5 0 0 1-.314.464L14.5 8l.186.464-.003.001-.006.003-.023.009a12.435 12.435 0 0 1-.397.15c-.264.095-.631.223-1.047.35-.816.252-1.879.523-2.71.523-.847 0-1.548-.28-2.158-.525l-.028-.01C7.68 8.71 7.14 8.5 6.5 8.5c-.7 0-1.638.23-2.437.477A19.626 19.626 0 0 0 3 9.342V15.5a.5.5 0 0 1-1 0V.5a.5.5 0 0 1 1 0v.282c.226-.079.496-.17.79-.26C4.606.272 5.67 0 6.5 0c.84 0 1.524.277 2.121.519l.043.018C9.286.788 9.828 1 10.5 1c.7 0 1.638-.23 2.437-.477a19.587 19.587 0 0 0 1.349-.476l.019-.007.004-.002h.001"/>
                                                    </svg>
                                                  <Accordion.Body>
                                                            <div className={styles.mb-3}>
                                                              <Form>
                                                          <Form.Group className="mb-3" controlId="formBasicEmail">
                                                            <Form.Label>Add your Answer</Form.Label>
                                                            <Form.Control type="text" as="textarea" rows={3} placeholder="Have some thing to say..." />
                                                        </Form.Group>
                                                      </Form>
                                                      <div className={styles.btn}>
                                                          <Button variant="primary" type="cancle">
                                                                Cancle
                                                          </Button>

                                                          <Button variant="primary" type="submit">
                                                                Submit 
                                                          </Button>
                                                      </div>
                                                              </div>
                                                  </Accordion.Body>
                                                </Accordion.Item>
                                                </Accordion>
                                    </div>
                                    </div>
                                    
                                 </div>
                                    
                                         
                                </Col>
                                </Row>
                                       <h5 className={styles.h3122}>View More Answers <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" className="bi bi-chevron-down" viewBox="0 0 16 16"> <path fillRule="evenodd" d="M1.646 4.646a.5.5 0 0 1 .708 0L8 10.293l5.646-5.647a.5.5 0 0 1 .708.708l-6 6a.5.5 0 0 1-.708 0l-6-6a.5.5 0 0 1 0-.708z"/></svg></h5>
                               <div className={styles.addans}>
                                            <Form>
                                                <Form.Group className="mb-3" controlId="formBasicEmail">
                                                  <Form.Label>Add your Answer</Form.Label>
                                                  <Form.Control type="text" as="textarea" rows={3} placeholder="Have some thing to say..." />
                                               </Form.Group>
                                            </Form>
                                            <Button variant="primary" type="submit">
                                                  Submit Answer
                                            </Button>

                               </div>      
                               <div className={styles.scroll}>
                               <Carousel responsive={responsive}>
                                    <div> 
                                      <div className={styles.scrollbx}>
                                        <h5>
                                         Q. What is the differnce between 2018 petrol baleno...
                                        </h5>
                                        <div className={styles.scrollbx2}>
                                        <span>R</span>
                                        <p>Asked by himanshu 4 questions</p>
                                        </div>
                                      </div>
                                    </div>
                                    <div>
                                      <div className={styles.scrollbx}>
                                        <h5>
                                         Q. What is the differnce between 2018 petrol baleno...
                                        </h5>
                                        <div className={styles.scrollbx2}>
                                        <span>R</span>
                                        <p>Asked by himanshu 4 questions</p>
                                        </div>
                                      </div>
                                      </div> 
                                    <div> <div className={styles.scrollbx}>
                                        <h5>
                                         Q. is there any change in baleno 2019 interior ...
                                        </h5>
                                        <div className={styles.scrollbx2}>
                                        <span>R</span>
                                        <p>Asked by himanshu 4 questions</p>
                                        </div>
                                      </div></div>
                                    <div> <div className={styles.scrollbx}>
                                        <h5>
                                         Q. What is the differnce between 2018 petrol baleno...
                                        </h5>
                                        <div className={styles.scrollbx2}>
                                        <span>R</span>
                                        <p>Asked by himanshu 4 questions</p>
                                        </div>
                                      </div></div>
                               </Carousel>
                                                                  
                              </div> 
                              <div className={styles.downbar}>
                                <p>Community Discussions</p>
                                
                                </div>                      
            </Col>
            <Col md={3} sm={12}>
                    <div>
                    <div className={styles.header}>
                                        <p>Trending Maruti Suzuki Cars</p>
                                       <span>Views All</span>
                                    </div>
                
                <div className={styles.sidebar}>
             <Row>
                <Col md={4} sm={4} xs={4} >
                  <div className={styles.pic}>
                    <img src="/c3.jfif"></img>
                  </div>
                </Col>
                <Col md={8} sm={8} xs={8} >
                  <div>
                    <p className={styles.hr}>Swift</p>
                    <p className={styles.hr2}>Rs.5.47 Lakh</p>
                  </div>
                </Col><hr></hr>
               </Row>
               <Row>
                <Col md={4} sm={4} xs={4}>
                  <div className={styles.pic}>
                  <img src="/c6.jfif"></img>
                  </div>
                </Col>
                <Col md={8} sm={8} xs={8}>
                  <div>
                    <p className={styles.hr}>Wagnor</p>
                    <p className={styles.hr2}>Rs 4.88 Lakh</p>
                  </div>
                </Col><hr></hr>
               </Row>
               <Row>
                    <Col md={4} sm={4} xs={4}>
                        <div className={styles.pic}>
                          <img src="c4.jfif"></img>
                        </div>
                    </Col>
                    <Col md={8} sm={8} xs={8}>
                          <div>
                            <p className={styles.hr}>Desire</p>
                            <p className={styles.hr2}>Rs 8.05 Lakh</p>
                          </div>
                    </Col>
                      <hr></hr>
               </Row>
               <Row>
                    <Col md={4} sm={4} xs={4}>
                        <div className={styles.pic}>
                           <img src="/c3.jfif"></img>
                        </div>
                    </Col>
                <Col md={8} sm={8} xs={8}>
                  <div>
                    <p className={styles.hr}>Ignis</p>
                    <p className={styles.hr2}>Rs.5.88 Lakh</p>
                  </div>
                </Col><hr></hr>
               </Row>
               <Row>
                <Col md={4} sm={4} xs={4}>
                  <div className={styles.pic}>
                  <img src="/c2.jfif"></img>
                  </div>
                </Col>
                <Col md={8} sm={8} xs={8}>
                  <div>
                    <p className={styles.hr}>Alto</p>
                    <p className={styles.hr2}>Rs.3.05 Lakh</p>
                  </div>
                </Col><hr></hr>
               </Row>
               <Row>
                <Col md={4} sm={4} xs={4}>
                  <div className={styles.pic}>
                  <img src="/c1.jfif"></img>
                  </div>
                </Col>
                <Col md={8} sm={8} xs={8}>
                  <div>
                    <p className={styles.hr}>Ignis</p>
                    <p className={styles.hr2}>Rs.5.88 Lakh</p>
                  </div>
                </Col><hr></hr>
               </Row>
               <Row>
                <Col md={4} sm={4} xs={4} >
                  <div className={styles.pic}>
                  <img src="/c3.jfif"></img>
                  </div>
                </Col>
                <Col md={8} sm={8} xs={8}>
                  <div>
                    <p className={styles.hr}>Swift</p>
                    <p className={styles.hr2}>Rs.5.05 Lakh</p>
                  </div>
                </Col><hr></hr>
               </Row>
               <Row>
                            <Col md={4} sm={4} xs={4}>
                              <div className={styles.pic}>
                              <img src="/c6.jfif"></img>
                              </div>
                            </Col>
                            <Col md={8} sm={8} xs={8}>
                              <div>
                                <p className={styles.hr}>Wagnor </p>
                                <p className={styles.hr2}>Rs.1.90 Lakh</p>
                              </div>
                            </Col><hr></hr>
                          </Row>
                          <Row>
                            <Col md={4} sm={4} xs={4}>
                              <div className={styles.pic}>
                              <img src="/c4.jfif"></img>
                              </div>
                            </Col>
                            <Col md={8} sm={8} xs={8}>
                              <div>
                                <p className={styles.hr}>Desire</p>
                                <p className={styles.hr2}>Rs.3.01 Lakh</p>
                              </div>
                              
                            </Col><hr></hr>
                          </Row>
                          
                          </div>
                          
                    </div>
            </Col>
        </Row>
        </div>                     
     </Container>                                         
                                             
      <main className={styles.main}>
    
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

